### ISSUE TITLE
atom-haskell project

### ISSUE THREAD

**Issue by lierdakil** [atom-haskell/haskell-debug#10]
Hi. I was wondering if you'd be interested in joining atom-haskell.

I love what you're doing here, but some code is painfully hacky. So I was thinking, maybe we could collaborate on improving ide-haskell's API and possibly integrating this with ide-haskell-repl (as in "ability to use ide-haskell-repl instead of a terminal" not as in "merge packages")?

FWIW, I've been doing [some work](https://github.com/atom-haskell/ide-haskell/pull/199) on managing tooltip provider priorities, so that could at least make [this hack](https://github.com/ThomasHickman/haskell-debug/blob/master/lib/TooltipOverride.ts) unnecessary. Let me know what you think!

**Comment by ThomasHickman** [comment]
Hi, I'd be interested in joining atom-haskell!

I agree that some parts my code are quite hacky, especially the TooltipOverride class. It would also be cool to have this package work with `ide-haskell-repl`, with `ide-haskell-repl` working like an in-editor terminal. I'll be free have a look at doing this in about 2 weeks time when I'll be off for the easter vacation (I'm a university student).

In the meantime, do you think it's worth transferring `haskell-debug` to the `atom-haskell` organisation?

**Comment by lierdakil** [comment]
> I'll be free have a look at doing this in about 2 weeks time 

For reference, ide-haskell-repl doesn't provide a public API at the moment, but it isn't hard to implement. The only question is, what that API should look like. I'll try to see if I can manage to draft something in the meantime.

> In the meantime, do you think it's worth transferring haskell-debug to the atom-haskell organisation?

Well, it's entirely up to you if you want to do that. Atom handles repository transfers very well, so there would be little to no difficulty in doing that (you don't even have to change `package.json` right away, since github will handle redirects transparently).

There is a good reason to do that though. Having the project in an organization gives at least some reassurance that project won't die without a maintainer, since there are several people who have access to management. So for instance, if you're busy with your thesis or something, and an urgent need for some changes arises (f.ex. Atom makes breaking changes to API), another member could  go in and fix that without bothering you.

I've sent you an invitation to atom-haskell. You should be able to create repositories on there, so it should be possible to transfer as well, if you choose to do so.
