### ISSUE TITLE
Runnding Debug Command Throws Exception

### ISSUE THREAD

**Issue by Cedware** [atom-haskell/haskell-debug#5]
Running "Haskell: Debug" causes the following exception:

> TypeError: Cannot read property 'handle' of undefined
>     at new a (C:\Users\cke.atom\packages\haskell-debug\node_modules\draggable\dist\draggable.min.js:1:429)
>     at new CurrentVariablesView (C:\Users\cke.atom\packages\haskell-debug\lib\views\CurrentVariablesView.js:22:26)
>     at new Debugger (C:\Users\cke.atom\packages\haskell-debug\lib\Debugger.js:24:37)
>     at atom-text-editor.Main.commands.debug (C:\Users\cke.atom\packages\haskell-debug\lib\main.js:32:30)
>     at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:260:29)
>     at C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:3:61
>     at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
>     at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
>     at space-pen-div.atom.commands.add.core:confirm (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
>     at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:260:29)
>     at C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:3:61
>     at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
>     at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
>     at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:98:36)
>     at HTMLDocument.<anonymous> (C:\Users\cke\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by ThomasHickman** [comment]
I corrected some code, so that it works with a new update of Draggable (4.1.0), if you update, it should work :)
